version: '3.9'

services:
  db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
