###LOGIN
GET http://localhost:8080/clients/login
Content-Type: application/json

{
  "email": "test3@mpp.com",
  "password": "client3"
}

###LOGOUT
POST http://localhost:8080/clients/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0M0BtcHAuY29tIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTY4NTc4OTc5MiwiZXhwIjoxNjg1NzkzMzkyfQ.DqiwuVLEBSSc2cdsrIOOTwzX-eA5j_8NprztUP5JDFpFL25U5p3DE26mKbUcqrLUBKYB6gv-_aTddI-5IATX3A

###WITHDRAW
PUT http://localhost:8080/clients/3/withdraw?amount=5.5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0M0BtcHAuY29tIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTY4NTc4OTc5MiwiZXhwIjoxNjg1NzkzMzkyfQ.DqiwuVLEBSSc2cdsrIOOTwzX-eA5j_8NprztUP5JDFpFL25U5p3DE26mKbUcqrLUBKYB6gv-_aTddI-5IATX3A

###FIND BY ID
GET http://localhost:8080/clients/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg1Nzg5NzcxLCJleHAiOjE2ODU3OTMzNzF9.gvD_s9d7GLatY52aSwhI1iuR0WwS3Kc0a-uXm7tqwxIiiXJgr2sZva8GjoEHOcUTxco2TR-NZuDxDsdsZChxlQ

###LIST ALL
GET http://localhost:8080/clients?start=0&count=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg1NzkyMDE0LCJleHAiOjE2ODU3OTU2MTR9.8uYkT0jhwfTJGr2fbYaQGbuiC-VQmUl1RLbQmMh81d-UY0BBvneRtcmQomCU6DbMy_lOaWu_0HnZMt6xM4I3CA

###DELETE
DELETE http://localhost:8080/clients/2
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg1NzIwODE1LCJleHAiOjE2ODU3MjQ0MTV9.IrCWtdHMRlayWgpNmSnOU5_HPay4Sijyrimkg0ghD1Rvy_YEw-FpHncKSejvfMNY-jUndh4gILmMHTvIdRlwBg

###ADD
POST http://localhost:8080/clients
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg1NzIwODE1LCJleHAiOjE2ODU3MjQ0MTV9.IrCWtdHMRlayWgpNmSnOU5_HPay4Sijyrimkg0ghD1Rvy_YEw-FpHncKSejvfMNY-jUndh4gILmMHTvIdRlwBg

{
  "lastName": "POST",
  "firstName": "POST",
  "phoneNumber": "07noidoi",
  "email": "post@testing.com",
  "password": "admin",
  "balance": 10,
  "address": {
    "county": "Test1",
    "city": "Test1",
    "street": "Test1",
    "number": 6,
    "ZIPCode": "123456"
  }
}

###UPDATE
PUT http://localhost:8080/clients/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg1NzIwODE1LCJleHAiOjE2ODU3MjQ0MTV9.IrCWtdHMRlayWgpNmSnOU5_HPay4Sijyrimkg0ghD1Rvy_YEw-FpHncKSejvfMNY-jUndh4gILmMHTvIdRlwBg

{
  "lastName": "PUT",
  "firstName": "PUT",
  "phoneNumber": "07noidoi",
  "email": "put@mpp.com",
  "password": "admin",
  "balance": 15.1,
  "address": {
    "county": "Test",
    "city": "Test",
    "street": "Test",
    "number": 6,
    "ZIPCode": "1234"
  }
}