###LOGIN
POST http://localhost:8080/clients/login
Content-Type: application/json

{
  "email": "test3@mpp.com",
  "password": "client3"
}

###LOGOUT
POST http://localhost:8080/clients/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0M0BtcHAuY29tIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTY4NTc4OTc5MiwiZXhwIjoxNjg1NzkzMzkyfQ.DqiwuVLEBSSc2cdsrIOOTwzX-eA5j_8NprztUP5JDFpFL25U5p3DE26mKbUcqrLUBKYB6gv-_aTddI-5IATX3A

###WITHDRAW
PUT http://localhost:8080/clients/3/withdraw?amount=5.5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0M0BtcHAuY29tIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTY4NTc4OTc5MiwiZXhwIjoxNjg1NzkzMzkyfQ.DqiwuVLEBSSc2cdsrIOOTwzX-eA5j_8NprztUP5JDFpFL25U5p3DE26mKbUcqrLUBKYB6gv-_aTddI-5IATX3A

###FIND BY ID
GET http://localhost:8080/clients/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2MDU5NzQyLCJleHAiOjE2ODYwNjMzNDJ9.8lUcKjB1SVRFWLfyBurcsQMSIgRKsfGqfruM_rU07AjU8u_4D1KnW5KTj8XGubH47CW7_prxUqKXNy9htvYRXg

###LIST ALL
GET http://localhost:8080/clients?start=0&count=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2MTIzOTg3LCJleHAiOjE2ODYxMjc1ODd9.hGM8jnRAxfKsA25udXeLCJMOyFoU3gvz0haujEVHIy1bcO4-WAZRA84SI_R8b4fPVgs3deWTtVXY32MXOr22Bw

###DELETE
DELETE http://localhost:8080/clients/2
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2MDU4OTg3LCJleHAiOjE2ODYwNjI1ODd9.6ZeElH7BEOYZ2ac_DZLBQyM729HUDjZfzW7TzBNn8kV9Wvvd1Aa8Jdn9NyzT3qD5kI67uvgPC9p_PB2M4vnPBQ

###ADD
POST http://localhost:8080/clients
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2MDU5MjQ2LCJleHAiOjE2ODYwNjI4NDZ9.wDah0IJi7YzNqwkjYtRYSPkA3V4rmlfXVXZGm8slyUHUuuY8rqsiLz0_5cKfXGCX3TT3RHvLIql4owxA1ONB5w

{
  "lastName": "POST",
  "firstName": "POST",
  "phoneNumber": "07noidoi",
  "email": "post@testing.com",
  "password": "admin",
  "balance": 10,
  "address": {
    "county": "Test1",
    "city": "Test1",
    "street": "Test1",
    "number": 6,
    "ZIPCode": "123456"
  }
}

###UPDATE
PUT http://localhost:8080/clients/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2MDU5MjQ2LCJleHAiOjE2ODYwNjI4NDZ9.wDah0IJi7YzNqwkjYtRYSPkA3V4rmlfXVXZGm8slyUHUuuY8rqsiLz0_5cKfXGCX3TT3RHvLIql4owxA1ONB5w

{
  "lastName": "PUT",
  "firstName": "PUT",
  "phoneNumber": "07noidoi",
  "email": "put@mpp.com",
  "password": "admin",
  "balance": 15.1,
  "address": {
    "county": "Test",
    "city": "Test",
    "street": "Test",
    "number": 6,
    "ZIPCode": "1234"
  }
}