###FIND BY ID
GET http://localhost:8080/invoices/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTY4NTM4NjQzMywiZXhwIjoxNjg1MzkwMDMzfQ.PtBRK97pHcsGlehd2riOBXnDSTwzbK8eAYOge0BIL-Y8EuvSBz3wFgF-YiWQQvfqt0z6urbkmn-79_8WfQaw3g

###LIST ALL
GET http://localhost:8080/invoices?start=0&count=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2MTIwNDQ1LCJleHAiOjE2ODYxMjQwNDV9.ctQCT3XhB95rRCZynFjPr6tympycOEQiRibTehjdZZjUowJKDp99VhBffKsTOA-PVarYmRdaRXV5LKcFeafbAw

###ADD
POST http://localhost:8080/invoices
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImVtcGxveWVlIiwiaWF0IjoxNjg1NzkxOTg3LCJleHAiOjE2ODU3OTU1ODd9.8bVYNZhDqlSZB3g0ETj1O5rukGLXynEBRBMWMcWFvF4GPJbOW4zgKINEUhNB6imRujyfbs3_xM6ChM69OEk_PA

{
  "idClient": 5,
  "idEmployee": 5,
  "categoryType": "PLASTIC_AND_BOTTLE",
  "penaltyPoints": 2,
  "listItems": [
    {"id": 6, "number": 5},
    {"id": 7, "number": 3}
  ]
}