###FIND BY CATEGORY
GET http://localhost:8080/items/findAllByCategory?categoryType=PLASTIC_AND_BOTTLE
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwicm9sZSI6ImVtcGxveWVlIiwiaWF0IjoxNjg1Nzg5ODQ2LCJleHAiOjE2ODU3OTM0NDZ9.cFy14ejmsRTMeUGnfgLBOT62DugpNWcYhff_evRWuFNANroXcXgeN-Y0HzsLiRBCDAwpio8nUOi7SqMru_VZlQ
