###GET
GET http://localhost:8080/clients/login
Content-Type: application/json

{
  "email": "test1@mpp.com",
  "password": "client1"
}

###GET
GET http://localhost:8080/clients/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwiaWF0IjoxNjg1Mjk1NzM1LCJleHAiOjE2ODUyOTkzMzV9.6IUeKdlaSEAQnASido25fRdq6DT6upl-i2uuuIMoC2N4BBpeG8L8F3p1c0S6ZEN8ecaUFNoHVDdjZgxlAlDO0A

###GET
GET http://localhost:8080/clients?start=0&count=10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwiaWF0IjoxNjg1Mjk4MDExLCJleHAiOjE2ODUzMDE2MTF9.334mCPPrSikM9nzl8RDmUqtVvAj22yUf9ZXN3WaTCYIKmjNGRWRGjHxPOeajuujc9ThgKQqqVm6bSKPwwLv_2g

###DELETE
DELETE http://localhost:8080/clients/2
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwiaWF0IjoxNjg1Mjk0OTA3LCJleHAiOjE2ODUyOTg1MDd9.sOp9_AQnzFTRHt7tQLSrvWY5TloMkqx2xQDeSnfzb_9K3s-ejnhkvt8F-MvIJEoQnLulqfq1oreighfWsl1-Bw

###POST
POST http://localhost:8080/clients
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwiaWF0IjoxNjg1Mjk4MDExLCJleHAiOjE2ODUzMDE2MTF9.334mCPPrSikM9nzl8RDmUqtVvAj22yUf9ZXN3WaTCYIKmjNGRWRGjHxPOeajuujc9ThgKQqqVm6bSKPwwLv_2g

{
  "lastName": "POST",
  "firstName": "POST",
  "phoneNumber": "07noidoi",
  "email": "post@testing.com",
  "password": "admin",
  "balance": 10,
  "address": {
    "county": "Test1",
    "city": "Test1",
    "street": "Test1",
    "number": 6,
    "ZIPCode": "123456"
  }
}

###PUT
PUT http://localhost:8080/clients/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MUBtcHAuY29tIiwiaWF0IjoxNjg1Mjk0OTA3LCJleHAiOjE2ODUyOTg1MDd9.sOp9_AQnzFTRHt7tQLSrvWY5TloMkqx2xQDeSnfzb_9K3s-ejnhkvt8F-MvIJEoQnLulqfq1oreighfWsl1-Bw

{
  "lastName": "PUT",
  "firstName": "PUT",
  "phoneNumber": "07noidoi",
  "email": "put@mpp.com",
  "password": "admin",
  "balance": 15.1,
  "address": {
    "county": "Test",
    "city": "Test",
    "street": "Test",
    "number": 6,
    "ZIPCode": "1234"
  }
}