###GET
GET http://localhost:8080/clients/all
Content-Type: application/json

###GET
GET http://localhost:8080/clients/1
Content-Type: application/json

###GET
GET http://localhost:8080/clients?start=1&count=2
Content-Type: application/json

###DELETE
DELETE http://localhost:8080/clients/2

###POST
POST http://localhost:8080/clients
Content-Type: application/json

{
  "lastName": "TestPosted",
  "firstName": "TestPosted",
  "phoneNumber": "07noidoi",
  "email": "test@mpp.com",
  "password": "admin",
  "balance": 15.1,
  "address": {
    "county": "Test",
    "city": "Test",
    "street": "Test",
    "number": 6,
    "id": 1,
    "ZIPCode": "1234"
  }
}

###PUT
PUT http://localhost:8080/clients/1
Content-Type: application/json

{
        "lastName": "Testputted",
        "firstName": "TestPutted",
        "phoneNumber": "07noidoi",
        "email": "test@mpp.com",
        "password": "admin",
        "balance": 15.1,
        "address": {
            "county": "Test",
            "city": "Test",
            "street": "Test",
            "number": 6,
            "id": 1,
            "ZIPCode": "1234"
        },
        "id": 1
    }