###GET
GET http://localhost:8080/addresses
Content-Type: application/json

###GET
GET http://localhost:8080/invoices?start=0&count=3
Content-Type: application/json

###GET
GET http://localhost:8080/invoices/1
Content-Type: application/json

###POST
POST http://localhost:8080/clients
Content-Type: application/json

{
  "lastName": "POST",
  "firstName": "POST",
  "phoneNumber": "0777777777",
  "email": "post@mpp.com",
  "passwordC": "post",
  "balance": 10.5,
  "idAddress": 10
}

###PUT
PUT http://localhost:8080/clients/1
Content-Type: application/json

{
  "lastName": "POST",
  "firstName": "POST",
  "phoneNumber": "0777777777",
  "email": "post@mpp.com",
  "passwordC": "post",
  "balance": 10.5,
  "idAddress": 10
}

###DELETE
DELETE http://localhost:8080/employees/3
Content-Type: application/json

###GET
GET http://localhost:8080/clients/1
Content-Type: application/json

###GET
GET http://localhost:8080/items/findAllByCategory?categoryType=PLASTIC_AND_BOTTLE
Content-Type: application/json

###POST
POST http://localhost:8080/invoices
Content-Type: application/json

{
  "idClient": 5,
  "idEmployee": 5,
  "categoryType": "PLASTIC_AND_BOTTLE",
  "penaltyPoints": 2,
  "listItems": [
    {"id": 6, "number": 5},
    {"id": 7, "number": 3}
  ]
}
